# Generated by Django 5.1.7 on 2025-03-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_user_options_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashed_password',
        ),
    ]
