# Generated by Django 5.1.7 on 2025-03-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_remove_user_hashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default='2025-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='models.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersex'), ('O', 'Other'), ('U', 'Unspecified'), ('P', 'Prefer Not To Say')], default='M', max_length=7),
            preserve_default=False,
        ),
    ]
