# Generated by Django 4.2.10 on 2025-04-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_imageprediction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageprediction',
            table='image_prediction',
        ),
    ]
