# Generated by Django 4.2.10 on 2025-04-11 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_imageprediction_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='user',
            field=models.ForeignKey(default='119f1ea1332d41da8a588963fb1831b0', on_delete=django.db.models.deletion.CASCADE, related_name='image_predictions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='imageprediction',
            table=None,
        ),
    ]
