# Generated by Django 4.2.10 on 2025-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_imageprediction_created_by_imageprediction_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageprediction',
            table='image_prediction',
        ),
    ]
