# Generated by Django 4.2.10 on 2025-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_imageprediction_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='created_by',
            field=models.CharField(default='o', max_length=100),
            preserve_default=False,
        ),
    ]
