# Generated by Django 4.2.10 on 2025-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_imageprediction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
