name: Turn Off ECS Tasks

on:
  workflow_dispatch:

jobs:
  turn-off-ecs-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update ECS service desired count to 0
        run: |
          aws ecs update-service \
            --cluster my-cluster \
            --service my-service \
            --desired-count 0